### ISSUE TITLE
Plugin can't be enabled (?)

### ISSUE THREAD

**Issue by Nicodoff** [ThePsyKai/ProjectXIR#1]
so like i tried installing this in two different blender versions and when i am about to enable it, it gives me the same error 
![image](https://user-images.githubusercontent.com/110596131/182799958-4f195d43-520b-4121-a7d2-db1e3a910106.png)

**Comment by YAKgamer** [comment]
same

**Comment by ThePsyKai** [comment]
It currently only works for Blender 2.92. But I will look into this.

> so like i tried installing this in two different blender versions and when i am about to enable it, it gives me the same error ![image](https://user-images.githubusercontent.com/110596131/182799958-4f195d43-520b-4121-a7d2-db1e3a910106.png)

**Comment by ThePsyKai** [comment]
It currently only works for Blender 2.92. But I will look into this. Which version of blender are you using?

> so like i tried installing this in two different blender versions and when i am about to enable it, it gives me the same error ![image](https://user-images.githubusercontent.com/110596131/182799958-4f195d43-520b-4121-a7d2-db1e3a910106.png)

**Comment by ThePsyKai** [comment]
> It currently only works for Blender 2.92. But I will look into this. Which version of blender are you using?
> 
> > so like i tried installing this in two different blender versions and when i am about to enable it, it gives me the same error ![image](https://user-images.githubusercontent.com/110596131/182799958-4f195d43-520b-4121-a7d2-db1e3a910106.png)

Never mind I'm blind. an update for Blender 3.0 is in progress.
